apiVersion: v1
kind: PersistentVolume
metadata:
  name: survey-django-pv0
  labels:
    io.kompose.service: survey-django-pv0
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ec2-user/srv/survey" 

