apiVersion: v1
kind: PersistentVolume
metadata:
  name: survey-rabbitmq-pv0
  labels:
    io.kompose.service: survey-rabbitmq-pv0 
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ec2-user/watch-rabbitmq.sh"
