apiVersion: v1
kind: PersistentVolume
metadata:
  name: survey-celery-pv0
  labels:
    io.kompose.service: survey-celery-pv0
spec:
  storageClassName: ""
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ec2-user/srv/survey"
