apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /usr/bin/kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: survey-django
  name: survey-django
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: survey-django
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /usr/bin/kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/opt-default: "true"
        io.kompose.service: survey-django
    spec:
      containers:
        - args:
            - /start.sh
          env:
            - name: APP_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: APP_SECRET_KEY
                  name: opt-enviroments-development-env
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: opt-enviroments-development-env
            - name: MYSQL_LOCAL_HOST
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_LOCAL_HOST
                  name: opt-enviroments-development-env
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASSWORD
                  name: opt-enviroments-development-env
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PORT
                  name: opt-enviroments-development-env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: opt-enviroments-development-env
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: opt-enviroments-development-env
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_DEFAULT_PASS
                  name: opt-enviroments-development-env
            - name: RABBITMQ_DEFAULT_PORT
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_DEFAULT_PORT
                  name: opt-enviroments-development-env
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_DEFAULT_USER
                  name: opt-enviroments-development-env
            - name: RABBITMQ_DEFAULT_VHOST
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_DEFAULT_VHOST
                  name: opt-enviroments-development-env
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_HOST
                  name: opt-enviroments-development-env
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  key: REDIS_DB
                  name: opt-enviroments-development-env
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: REDIS_HOST
                  name: opt-enviroments-development-env
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PORT
                  name: opt-enviroments-development-env
          image: 363806660710.dkr.ecr.ap-southeast-1.amazonaws.com/rpp-prod-mainapp:1.1 
          name: survey-django
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /srv/survey
              name: survey-django-claim0
            - mountPath: /etc/supervisor/conf.d
              name: survey-django-claim1
            - mountPath: /var/log
              name: survey-django-claim2
      restartPolicy: Always
      volumes:
        - name: survey-django-claim0
          persistentVolumeClaim:
            claimName: survey-django-claim0
        - name: survey-django-claim1
          persistentVolumeClaim:
            claimName: survey-django-claim1
        - name: survey-django-claim2
          persistentVolumeClaim:
            claimName: survey-django-claim2
status: {}
